name: Antarctic Science Platform Data Catalog
description: A preliminary, incomplete, catalogue of datasets that have been downloaded or created for ASP projects that are, or can be made, available to other ASP researchers
markdown: kramdown